### ISSUE TITLE
変換機能の拡張：中国語の異体字変換機能の追加

### ISSUE THREAD

**Issue by kyubey1228** [kyubey1228/unihan_lang#11]
中国語の異体字変換機能を追加したい

目的：
- 中国語の繁体字、簡体字の変換機能を実装する

タスク：
1. 中国語の異体字のマッピングデータを作成または入手する
   (例: 録⇔彔、峰⇔峯、裏⇔裡 など)
2. 異体字変換のロジックを実装する
3. ユーザーインターフェース（メソッド）を設計し、実装する
4. 単体テストを作成し、変換の正確性を確認する
5. 既存の繁体字⇔簡体字変換機能との統合をテストする
6. ドキュメントを更新し、新機能の使用方法を説明する

**Comment by kaibadash** [comment]
あってもよいとおもいます！ 僕には単純に知識不足でどういう用途で使うのかわからないですが…
関西弁翻訳みたいなもんでしょうか？

> 中国語の異体字のマッピングデータを作成または入手する

これはunihan gemなのでunihanでできる範囲に留めたい気持ち…。
すでに traditional_characters.txt があるのもちょっと微妙な気もします。

**Comment by kyubey1228** [comment]
ありがとうございます、一旦本件はunihan_langの領域を超えてるかなーと思いましたのでクローズします
